# fly.toml file generated for eskridge-db on 2022-09-02T16:48:08-05:00

app          = "eskridge-db"
kill_signal  = "SIGINT"
kill_timeout = 5

[mounts]
  destination = "/data"
  source      = "eskridge_data"

[env]
  MYSQL_DATABASE = "ghost"
  MYSQL_USER     = "ghost_user"

[build]
  image = "mysql:8"

[experimental]
  cmd = [
    "--default-authentication-plugin",
    "mysql_native_password",
    "--datadir",
    "/data/mysql",
  ]
